# Docker Compose Definitions for local Developer Environment
version: '3'

services:

  orchestrator_app:
    container_name: neoway_app
    build:
      context: ./
    command: tail -f /dev/null
    working_dir: /neoway
    env_file:
      - .env
    ports:
      - "5001:5001"
    volumes:
      - ./:/neoway